/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eKiip_autodefs.h"
#include "s3eEdk.h"
#include "s3eKiip.h"
//Declarations of Init and Term functions
extern s3eResult s3eKiipInit();
extern void s3eKiipTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult s3eKiipInitWithKeys_wrap(const char* appKey, const char* appSecret)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipInitWithKeys"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipInitWithKeys, 2, appKey, appSecret);
}

static s3eResult s3eKiipSaveMoment_wrap(const char* momentID)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSaveMoment"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSaveMoment, 1, momentID);
}

static s3eResult s3eKiipSaveMomentWithValue_wrap(const char* momentID, double* value)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSaveMomentWithValue"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSaveMomentWithValue, 2, momentID, value);
}

static void s3eKiipSetAutorotate_wrap(bool shouldAutoRotate)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSetAutorotate"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSetAutorotate, 1, shouldAutoRotate);
}

static void s3eKiipSetInterfaceOrientation_wrap(s3eUIInterfaceOrientation orientation)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSetInterfaceOrientation"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSetInterfaceOrientation, 1, orientation);
}

static void s3eKiipSetEmailAddress_wrap(const char* email)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSetEmailAddress"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSetEmailAddress, 1, email);
}

static void s3eKiipSetGender_wrap(const char* gender)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSetGender"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSetGender, 1, gender);
}

static void s3eKiipSetBirthday_wrap(const char* dob)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip func on main thread: s3eKiipSetBirthday"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eKiipSetBirthday, 1, dob);
}

#define s3eKiipInitWithKeys s3eKiipInitWithKeys_wrap
#define s3eKiipSaveMoment s3eKiipSaveMoment_wrap
#define s3eKiipSaveMomentWithValue s3eKiipSaveMomentWithValue_wrap
#define s3eKiipSetAutorotate s3eKiipSetAutorotate_wrap
#define s3eKiipSetInterfaceOrientation s3eKiipSetInterfaceOrientation_wrap
#define s3eKiipSetEmailAddress s3eKiipSetEmailAddress_wrap
#define s3eKiipSetGender s3eKiipSetGender_wrap
#define s3eKiipSetBirthday s3eKiipSetBirthday_wrap

#endif

void s3eKiipRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[11];
    funcPtrs[0] = (void*)s3eKiipInitWithKeys;
    funcPtrs[1] = (void*)s3eKiipRegisterCallback;
    funcPtrs[2] = (void*)s3eKiipSaveMoment;
    funcPtrs[3] = (void*)s3eKiipSaveMomentWithValue;
    funcPtrs[4] = (void*)s3eKiipSetAutorotate;
    funcPtrs[5] = (void*)s3eKiipGetAutorotate;
    funcPtrs[6] = (void*)s3eKiipSetInterfaceOrientation;
    funcPtrs[7] = (void*)s3eKiipGetInterfaceOrientation;
    funcPtrs[8] = (void*)s3eKiipSetEmailAddress;
    funcPtrs[9] = (void*)s3eKiipSetGender;
    funcPtrs[10] = (void*)s3eKiipSetBirthday;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[11] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3eKiip", funcPtrs, sizeof(funcPtrs), flags, s3eKiipInit, s3eKiipTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eKiipStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eKiipRegisterExt;
    return 0;
}

int g_s3eKiipVal = s3eKiipStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eKiipRegisterExt();
}
#endif

#endif
