/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef LEADBOLTEXT_AUTODEFS_H
#define LEADBOLTEXT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_LEADBOLTEXT_NAME "LeadboltExt"
#define S3E_EXT_LEADBOLTEXT_HASH 0xb62b0a3d

#endif /* !LEADBOLTEXT_AUTODEFS_H */
