/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eKiip.h"


#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
// For MIPs (and WP8) platform we do not have asm code for stack switching
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL_LOCK
#endif
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eKiipInitWithKeys_t)(const char* appKey, const char* appSecret);
typedef       void(*s3eKiipRegisterCallback_t)(s3eKiipCallbackType callbackID, s3eCallback callbackFn, void* userData);
typedef  s3eResult(*s3eKiipSaveMoment_t)(const char* momentID);
typedef  s3eResult(*s3eKiipSaveMomentWithValue_t)(const char* momentID, double* value);
typedef       void(*s3eKiipSetAutorotate_t)(bool shouldAutoRotate);
typedef       bool(*s3eKiipGetAutorotate_t)();
typedef       void(*s3eKiipSetInterfaceOrientation_t)(s3eUIInterfaceOrientation orientation);
typedef s3eUIInterfaceOrientation(*s3eKiipGetInterfaceOrientation_t)();
typedef       void(*s3eKiipSetEmailAddress_t)(const char* email);
typedef       void(*s3eKiipSetGender_t)(const char* gender);
typedef       void(*s3eKiipSetBirthday_t)(const char* dob);

/**
 * struct that gets filled in by s3eKiipRegister
 */
typedef struct s3eKiipFuncs
{
    s3eKiipInitWithKeys_t m_s3eKiipInitWithKeys;
    s3eKiipRegisterCallback_t m_s3eKiipRegisterCallback;
    s3eKiipSaveMoment_t m_s3eKiipSaveMoment;
    s3eKiipSaveMomentWithValue_t m_s3eKiipSaveMomentWithValue;
    s3eKiipSetAutorotate_t m_s3eKiipSetAutorotate;
    s3eKiipGetAutorotate_t m_s3eKiipGetAutorotate;
    s3eKiipSetInterfaceOrientation_t m_s3eKiipSetInterfaceOrientation;
    s3eKiipGetInterfaceOrientation_t m_s3eKiipGetInterfaceOrientation;
    s3eKiipSetEmailAddress_t m_s3eKiipSetEmailAddress;
    s3eKiipSetGender_t m_s3eKiipSetGender;
    s3eKiipSetBirthday_t m_s3eKiipSetBirthday;
} s3eKiipFuncs;

static s3eKiipFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x1680243d, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eKiip");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x1680243d, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eKiipAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eKiipInitWithKeys(const char* appKey, const char* appSecret)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[0] func: s3eKiipInitWithKeys"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eKiipInitWithKeys(appKey, appSecret);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eKiipRegisterCallback(s3eKiipCallbackType callbackID, s3eCallback callbackFn, void* userData)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[1] func: s3eKiipRegisterCallback"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eKiipRegisterCallback(callbackID, callbackFn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

s3eResult s3eKiipSaveMoment(const char* momentID)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[2] func: s3eKiipSaveMoment"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eKiipSaveMoment(momentID);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult s3eKiipSaveMomentWithValue(const char* momentID, double* value)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[3] func: s3eKiipSaveMomentWithValue"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eKiipSaveMomentWithValue(momentID, value);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eKiipSetAutorotate(bool shouldAutoRotate)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[4] func: s3eKiipSetAutorotate"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eKiipSetAutorotate(shouldAutoRotate);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

bool s3eKiipGetAutorotate()
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[5] func: s3eKiipGetAutorotate"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_s3eKiipGetAutorotate();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eKiipSetInterfaceOrientation(s3eUIInterfaceOrientation orientation)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[6] func: s3eKiipSetInterfaceOrientation"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eKiipSetInterfaceOrientation(orientation);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

s3eUIInterfaceOrientation s3eKiipGetInterfaceOrientation()
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[7] func: s3eKiipGetInterfaceOrientation"));

    if (!_extLoad())
        return s3eUIInterfaceOrientationUnknown;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eUIInterfaceOrientation ret = g_Ext.m_s3eKiipGetInterfaceOrientation();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eKiipSetEmailAddress(const char* email)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[8] func: s3eKiipSetEmailAddress"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eKiipSetEmailAddress(email);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eKiipSetGender(const char* gender)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[9] func: s3eKiipSetGender"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eKiipSetGender(gender);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eKiipSetBirthday(const char* dob)
{
    IwTrace(KIIP_VERBOSE, ("calling s3eKiip[10] func: s3eKiipSetBirthday"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eKiipSetBirthday(dob);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
