/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef IOSNATIVEEDK_AUTODEFS_H
#define IOSNATIVEEDK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSNATIVEEDK_NAME "iOSNativeEDK"
#define S3E_EXT_IOSNATIVEEDK_HASH 0x81b1ac2b

#endif /* !IOSNATIVEEDK_AUTODEFS_H */
