/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_LEADBOLTEXT_H
#define S3E_EXT_LEADBOLTEXT_H

#include <s3eTypes.h>

enum LeadboltCallback{
	LEADBOLT_RESUMED = 0,
	LEADBOLT_PAUSED,
	LEADBOLT_CLOSED = 0,
        LEADBOLT_PROGRESS,
        LEADBOLT_LOADED,
        LEADBOLT_FAILED,
        LEADBOLT_COMPLETED,
        LEADBOLT_AUDIOCLICKED,
        LEADBOLT_AUDIOCLOSED,
        LEADBOLT_AUDIOFAILED,
        LEADBOLT_AUDIOLOADED,
        LEADBOLT_AUDIOFINISHED,
        LEADBOLT_AUDIOPROGRESS,
        LEADBOLT_CALLBACK_MAX
};
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the LeadboltExt extension is available.
 */
s3eBool LeadboltExtAvailable();

s3eResult loadStartAd(const char* sectionid, const char* reengagementid, const char* audioid);

s3eResult loadAd(const char* sectionid);

s3eResult destroyAd(const char* sectionid);

s3eResult pauseAd(const char* sectionid);

s3eResult resumeAd(const char* sectionid);

s3eResult loadAudioAd(const char* sectionid);

s3eResult shakeMotionStarted(const char* sectionid);

s3eResult shakeMotionEnded(const char* sectionid);

s3eResult loadReEngagement(const char* sectionid);

s3eResult reEngagementLoaded(const char* sectionid);

s3eResult loadBanner(const char* sectionid);

s3eResult loadBannerWithMargin(const char* sectionid, int margin);

s3eResult setLandscapeMode(const char* newMode);

s3eResult setLocationControl(const char* newLocationControl);

S3E_END_C_DECL

#endif /* !S3E_EXT_LEADBOLTEXT_H */
