/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_GAMEPAD_H
#define S3E_EXT_GAMEPAD_H

#include <s3eTypes.h>
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the GamePad extension is available.
 */
s3eBool GamePadAvailable();

bool GamePad_IsConnected();

bool GamePad_Update(float dt);

float GamePad_GetStick1XAxis();

float GamePad_GetStick1YAxis();

float GamePad_GetStick2XAxis();

float GamePad_GetStick2YAxis();

float GamePad_GetLeftTrigger();

float GamePad_GetRightTrigger();

bool GamePad_GetButtonX();

bool GamePad_GetButtonY();

bool GamePad_GetButtonA();

bool GamePad_GetButtonB();

bool GamePad_GetButtonDPadLeft();

bool GamePad_GetButtonDPadRight();

bool GamePad_GetButtonDPadUp();

bool GamePad_GetButtonDPadDown();

bool GamePad_GetButtonLShoulderDown();

bool GamePad_GetButtonRShoulderDown();

bool GamePad_GetButtonStart();

bool GamePad_GetButtonSelect();

S3E_END_C_DECL

#endif /* !S3E_EXT_GAMEPAD_H */
