/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "LeadboltExt.h"


// For MIPs (and WP8) platform we do not have asm code for stack switching 
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*loadStartAd_t)(const char* sectionid, const char* reengagementid, const char* audioid);
typedef  s3eResult(*loadAd_t)(const char* sectionid);
typedef  s3eResult(*destroyAd_t)(const char* sectionid);
typedef  s3eResult(*pauseAd_t)(const char* sectionid);
typedef  s3eResult(*resumeAd_t)(const char* sectionid);
typedef  s3eResult(*loadAudioAd_t)(const char* sectionid);
typedef  s3eResult(*shakeMotionStarted_t)(const char* sectionid);
typedef  s3eResult(*shakeMotionEnded_t)(const char* sectionid);
typedef  s3eResult(*loadReEngagement_t)(const char* sectionid);
typedef  s3eResult(*reEngagementLoaded_t)(const char* sectionid);
typedef  s3eResult(*loadBanner_t)(const char* sectionid);
typedef  s3eResult(*loadBannerWithMargin_t)(const char* sectionid, int margin);
typedef  s3eResult(*setLandscapeMode_t)(const char* newMode);
typedef  s3eResult(*setLocationControl_t)(const char* newLocationControl);

/**
 * struct that gets filled in by LeadboltExtRegister
 */
typedef struct LeadboltExtFuncs
{
    loadStartAd_t m_loadStartAd;
    loadAd_t m_loadAd;
    destroyAd_t m_destroyAd;
    pauseAd_t m_pauseAd;
    resumeAd_t m_resumeAd;
    loadAudioAd_t m_loadAudioAd;
    shakeMotionStarted_t m_shakeMotionStarted;
    shakeMotionEnded_t m_shakeMotionEnded;
    loadReEngagement_t m_loadReEngagement;
    reEngagementLoaded_t m_reEngagementLoaded;
    loadBanner_t m_loadBanner;
    loadBannerWithMargin_t m_loadBannerWithMargin;
    setLandscapeMode_t m_setLandscapeMode;
    setLocationControl_t m_setLocationControl;
} LeadboltExtFuncs;

static LeadboltExtFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xb62b0a3d, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: LeadboltExt");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xb62b0a3d, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool LeadboltExtAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult loadStartAd(const char* sectionid, const char* reengagementid, const char* audioid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[0] func: loadStartAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_loadStartAd(sectionid, reengagementid, audioid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult loadAd(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[1] func: loadAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_loadAd(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult destroyAd(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[2] func: destroyAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_destroyAd(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult pauseAd(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[3] func: pauseAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_pauseAd(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult resumeAd(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[4] func: resumeAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_resumeAd(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult loadAudioAd(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[5] func: loadAudioAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_loadAudioAd(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult shakeMotionStarted(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[6] func: shakeMotionStarted"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_shakeMotionStarted(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult shakeMotionEnded(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[7] func: shakeMotionEnded"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_shakeMotionEnded(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult loadReEngagement(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[8] func: loadReEngagement"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_loadReEngagement(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult reEngagementLoaded(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[9] func: reEngagementLoaded"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_reEngagementLoaded(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult loadBanner(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[10] func: loadBanner"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_loadBanner(sectionid);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult loadBannerWithMargin(const char* sectionid, int margin)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[11] func: loadBannerWithMargin"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_loadBannerWithMargin(sectionid, margin);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult setLandscapeMode(const char* newMode)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[12] func: setLandscapeMode"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_setLandscapeMode(newMode);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult setLocationControl(const char* newLocationControl)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt[13] func: setLocationControl"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_setLocationControl(newLocationControl);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}
