/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "LeadboltExt_autodefs.h"
#include "s3eEdk.h"
#include "LeadboltExt.h"
//Declarations of Init and Term functions
extern s3eResult LeadboltExtInit();
extern void LeadboltExtTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult loadStartAd_wrap(const char* sectionid, const char* reengagementid, const char* audioid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: loadStartAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)loadStartAd, 3, sectionid, reengagementid, audioid);
}

static s3eResult loadAd_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: loadAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)loadAd, 1, sectionid);
}

static s3eResult destroyAd_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: destroyAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)destroyAd, 1, sectionid);
}

static s3eResult pauseAd_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: pauseAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)pauseAd, 1, sectionid);
}

static s3eResult resumeAd_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: resumeAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)resumeAd, 1, sectionid);
}

static s3eResult loadAudioAd_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: loadAudioAd"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)loadAudioAd, 1, sectionid);
}

static s3eResult shakeMotionStarted_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: shakeMotionStarted"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)shakeMotionStarted, 1, sectionid);
}

static s3eResult shakeMotionEnded_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: shakeMotionEnded"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)shakeMotionEnded, 1, sectionid);
}

static s3eResult loadReEngagement_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: loadReEngagement"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)loadReEngagement, 1, sectionid);
}

static s3eResult reEngagementLoaded_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: reEngagementLoaded"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)reEngagementLoaded, 1, sectionid);
}

static s3eResult loadBanner_wrap(const char* sectionid)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: loadBanner"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)loadBanner, 1, sectionid);
}

static s3eResult loadBannerWithMargin_wrap(const char* sectionid, int margin)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: loadBannerWithMargin"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)loadBannerWithMargin, 2, sectionid, margin);
}

static s3eResult setLandscapeMode_wrap(const char* newMode)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: setLandscapeMode"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)setLandscapeMode, 1, newMode);
}

static s3eResult setLocationControl_wrap(const char* newLocationControl)
{
    IwTrace(LEADBOLTEXT_VERBOSE, ("calling LeadboltExt func on main thread: setLocationControl"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)setLocationControl, 1, newLocationControl);
}

#define loadStartAd loadStartAd_wrap
#define loadAd loadAd_wrap
#define destroyAd destroyAd_wrap
#define pauseAd pauseAd_wrap
#define resumeAd resumeAd_wrap
#define loadAudioAd loadAudioAd_wrap
#define shakeMotionStarted shakeMotionStarted_wrap
#define shakeMotionEnded shakeMotionEnded_wrap
#define loadReEngagement loadReEngagement_wrap
#define reEngagementLoaded reEngagementLoaded_wrap
#define loadBanner loadBanner_wrap
#define loadBannerWithMargin loadBannerWithMargin_wrap
#define setLandscapeMode setLandscapeMode_wrap
#define setLocationControl setLocationControl_wrap

#endif

void LeadboltExtRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[14];
    funcPtrs[0] = (void*)loadStartAd;
    funcPtrs[1] = (void*)loadAd;
    funcPtrs[2] = (void*)destroyAd;
    funcPtrs[3] = (void*)pauseAd;
    funcPtrs[4] = (void*)resumeAd;
    funcPtrs[5] = (void*)loadAudioAd;
    funcPtrs[6] = (void*)shakeMotionStarted;
    funcPtrs[7] = (void*)shakeMotionEnded;
    funcPtrs[8] = (void*)loadReEngagement;
    funcPtrs[9] = (void*)reEngagementLoaded;
    funcPtrs[10] = (void*)loadBanner;
    funcPtrs[11] = (void*)loadBannerWithMargin;
    funcPtrs[12] = (void*)setLandscapeMode;
    funcPtrs[13] = (void*)setLocationControl;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[14] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("LeadboltExt", funcPtrs, sizeof(funcPtrs), flags, LeadboltExtInit, LeadboltExtTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int LeadboltExtStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&LeadboltExtRegisterExt;
    return 0;
}

int g_LeadboltExtVal = LeadboltExtStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    LeadboltExtRegisterExt();
}
#endif

#endif
