/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "iOSNativeEDK_autodefs.h"
#include "s3eEdk.h"
#include "iOSNativeEDK.h"
//Declarations of Init and Term functions
extern s3eResult iOSNativeEDKInit();
extern void iOSNativeEDKTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult Social_Twitter_wrap(const char* text)
{
    IwTrace(IOSNATIVEEDK_VERBOSE, ("calling iOSNativeEDK func on main thread: Social_Twitter"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)Social_Twitter, 1, text);
}

static s3eResult Social_Facebook_wrap(const char* text)
{
    IwTrace(IOSNATIVEEDK_VERBOSE, ("calling iOSNativeEDK func on main thread: Social_Facebook"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)Social_Facebook, 1, text);
}

static s3eResult iOS_Orientation_wrap(bool bLandscape)
{
    IwTrace(IOSNATIVEEDK_VERBOSE, ("calling iOSNativeEDK func on main thread: iOS_Orientation"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)iOS_Orientation, 1, bLandscape);
}

#define Social_Twitter Social_Twitter_wrap
#define Social_Facebook Social_Facebook_wrap
#define iOS_Orientation iOS_Orientation_wrap

#endif

void iOSNativeEDKRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[3];
    funcPtrs[0] = (void*)Social_Twitter;
    funcPtrs[1] = (void*)Social_Facebook;
    funcPtrs[2] = (void*)iOS_Orientation;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[3] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("iOSNativeEDK", funcPtrs, sizeof(funcPtrs), flags, iOSNativeEDKInit, iOSNativeEDKTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int iOSNativeEDKStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&iOSNativeEDKRegisterExt;
    return 0;
}

int g_iOSNativeEDKVal = iOSNativeEDKStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    iOSNativeEDKRegisterExt();
}
#endif

#endif
