/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EKIIP_AUTODEFS_H
#define S3EKIIP_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_KIIP_NAME "s3eKiip"
#define S3E_EXT_KIIP_HASH 0x1680243d

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eKiip", 11)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EKIIP_AUTODEFS_H */
